### ISSUE TITLE
Atualizar para Django 2.2

### ISSUE THREAD

**Issue by viniciusban** [vmesel/PyJobs#188]
Última versão da série 2.2

**Comment by vmesel** [comment]
```
 make test     
coverage run manage.py test
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/viniciusmesel/.virtualenvs/PyJobs-N2gnzKVY/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/viniciusmesel/.virtualenvs/PyJobs-N2gnzKVY/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/viniciusmesel/.virtualenvs/PyJobs-N2gnzKVY/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/viniciusmesel/.virtualenvs/PyJobs-N2gnzKVY/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/viniciusmesel/.virtualenvs/PyJobs-N2gnzKVY/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/viniciusmesel/.virtualenvs/PyJobs-N2gnzKVY/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/viniciusmesel/GitHub/PyJobs/pyjobs/marketing/models.py", line 50, in <module>
    class Share(models.Model):
  File "/Users/viniciusmesel/GitHub/PyJobs/pyjobs/marketing/models.py", line 51, in Share
    user_sharing = models.ForeignKey(User)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
make: *** [test] Error 1
```

**Comment by viniciusban** [comment]
Agora que a brincadeira começa. hehehe
