### ISSUE TITLE
Circle-ci rodando os testes

### ISSUE THREAD

**Issue by vmesel** [vmesel/PyJobs#94]
Agora que já temos os testes de volta a rodar podemos terminar a integração com o Circle-ci, que agora retorna o seguinte erro:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/circleci/repo/pyjobs/settings.py", line 25, in <module>
    SECRET_KEY = config('SECRET_KEY')
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/decouple.py", line 77, in __call__
    return self.get(*args, **kwargs)
  File "/home/circleci/repo/venv/lib/python3.6/site-packages/decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: SECRET_KEY option not found and default value was not defined.
Exited with code 1
```

**Comment by vmesel** [comment]
#96 resolveu essa issue!
